services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    hostname: "Api"
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - jenkins-net
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-vol:/var/lib/postgresql/data
    networks:
      - jenkins-net

networks:
  jenkins-net:
    external: true
volumes:
  db-vol:
  jenkins_home:

    
